# Generated by Django 3.2.25 on 2025-12-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_deleted',
        ),
    ]
