# Generated by Django 3.2.25 on 2025-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='tasks_task_created_69a8b4_idx'),
        ),
    ]
