# Generated by Django 3.2.25 on 2025-12-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_tasks_task_created_69a8b4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['user', 'created_at'], name='tasks_tip_user_id_7d752f_idx'),
        ),
    ]
